import { afterEach, describe, expect, test } from "bun:test";
import { createHash } from "node:crypto";
import { mkdir, mkdtemp, readFile, readdir, rm, stat, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, relative, resolve } from "node:path";

const ROOT = resolve(import.meta.dir, "..");
const CLI = join(ROOT, "cli", "playbook.ts");
const tempRoots: string[] = [];

afterEach(async () => {
  await Promise.all(tempRoots.splice(0).map((path) => rm(path, { recursive: true, force: true })));
});

async function fixture() {
  const path = await mkdtemp(join(tmpdir(), "keenko-playbook-test-"));
  tempRoots.push(path);
  await writeFile(join(path, "AGENTS.md"), "# Human AGENTS\n\nKeep me.\n");
  await writeFile(join(path, "CLAUDE.md"), "# Human CLAUDE\n\nKeep me too.\n");
  await writeFile(join(path, "CONTEXT.md"), "# Existing context\n\nKeep this context.\n");
  return path;
}

async function run(...args: string[]) {
  const proc = Bun.spawn([process.execPath, CLI, ...args], { stdout: "pipe", stderr: "pipe" });
  const [stdout, stderr, code] = await Promise.all([
    new Response(proc.stdout).text(),
    new Response(proc.stderr).text(),
    proc.exited,
  ]);
  return { stdout, stderr, code };
}

describe("consumer materialization", () => {
  test("install and same-source update are byte-idempotent and preserve human content", async () => {
    const target = await fixture();
    expect((await run("install", "--target", target)).code).toBe(0);
    const installed = await hashTree(target);
    expect(await readFile(join(target, "AGENTS.md"), "utf8")).toContain("Keep me.");
    expect(await readFile(join(target, "CLAUDE.md"), "utf8")).toContain("Keep me too.");
    expect(await readFile(join(target, "CONTEXT.md"), "utf8")).toContain("Keep this context.");

    expect((await run("install", "--target", target)).code).not.toBe(0);
    expect(await hashTree(target)).toEqual(installed);
    expect((await run("update", "--target", target)).code).toBe(0);
    expect(await hashTree(target)).toEqual(installed);
    expect((await run("update", "--target", target, "--apply")).code).toBe(0);
    expect(await hashTree(target)).toEqual(installed);
    expect((await run("check", "--target", target)).code).toBe(0);
  });

  test("preflights human-owned skill collisions without partial writes", async () => {
    const target = await fixture();
    await mkdir(join(target, ".claude", "skills", "confect"), { recursive: true });
    await writeFile(join(target, ".claude", "skills", "confect", "SKILL.md"), "human owned\n");
    const before = await hashTree(target);
    const result = await run("install", "--target", target);
    expect(result.code).not.toBe(0);
    expect(result.stderr).toContain("human-owned skill directory");
    expect(await hashTree(target)).toEqual(before);
    expect(await exists(join(target, ".playbook", "config.json"))).toBe(false);
  });

  test("detects managed-block tampering and retired generated skills", async () => {
    const target = await fixture();
    expect((await run("install", "--target", target)).code).toBe(0);
    const agents = await readFile(join(target, "AGENTS.md"), "utf8");
    await writeFile(join(target, "AGENTS.md"), agents.replace("Instruction precedence:", "Instruction precedence: REVERSED "));
    expect((await run("check", "--target", target)).code).not.toBe(0);

    expect((await run("update", "--target", target, "--apply")).code).toBe(0);
    const stale = join(target, ".agents", "skills", "retired-skill");
    await mkdir(stale, { recursive: true });
    await writeFile(join(stale, ".keenko-generated"), "generated by keenko-playbook\n");
    await writeFile(join(stale, "SKILL.md"), "stale\n");
    expect((await run("check", "--target", target)).code).not.toBe(0);
  });

  test("rejects unknown config schema versions before update", async () => {
    const target = await fixture();
    expect((await run("install", "--target", target)).code).toBe(0);
    const path = join(target, ".playbook", "config.json");
    const config = JSON.parse(await readFile(path, "utf8"));
    config.schemaVersion = 999;
    await writeFile(path, JSON.stringify(config, null, 2) + "\n");
    const result = await run("update", "--target", target);
    expect(result.code).not.toBe(0);
    expect(result.stderr).toContain("Unsupported .playbook config schemaVersion");
  });

  test("vendor adapters carry notices, provenance, and a closed authority guard into both harnesses", async () => {
    const target = await fixture();
    expect((await run("install", "--target", target)).code).toBe(0);
    for (const root of [".playbook/skills", ".agents/skills", ".claude/skills"]) {
      const dir = join(target, root, "grilling");
      expect(await exists(join(dir, "UPSTREAM_LICENSE"))).toBe(true);
      expect(await exists(join(dir, "UPSTREAM_PROVENANCE.json"))).toBe(true);
      const skill = await readFile(join(dir, "SKILL.md"), "utf8");
      expect(skill).toContain("Only route to skills that are actually installed");
      expect(skill).toContain("Do not commit, push, merge");
    }
  });
});

async function hashTree(root: string) {
  const out: Record<string, string> = {};
  for (const file of await findAllFiles(root)) {
    const rel = relative(root, file).replaceAll("\\", "/");
    out[rel] = createHash("sha256").update(await readFile(file)).digest("hex");
  }
  return out;
}

async function findAllFiles(root: string): Promise<string[]> {
  const out: string[] = [];
  if (!(await exists(root))) return out;
  for (const entry of await readdir(root, { withFileTypes: true })) {
    const path = join(root, entry.name);
    if (entry.isDirectory()) out.push(...await findAllFiles(path));
    else if (entry.isFile()) out.push(path);
  }
  return out.sort();
}

async function exists(path: string) {
  try { await stat(path); return true; } catch { return false; }
}
