import type { Tree } from "@nx/devkit";
import { createHash } from "node:crypto";
import { existsSync, readFileSync, readdirSync, statSync } from "node:fs";
import path from "node:path";

const PACKAGE_ROOT = packageRoot();
const START = "<!-- keenko:start -->";
const END = "<!-- keenko:end -->";

const VENDORED_SKILLS = {
  "ask-matt": "vendor/matt-pocock/skills/engineering/ask-matt",
  "code-review": "vendor/matt-pocock/skills/engineering/code-review",
  "codebase-design": "vendor/matt-pocock/skills/engineering/codebase-design",
  "diagnosing-bugs": "vendor/matt-pocock/skills/engineering/diagnosing-bugs",
  "domain-modeling": "vendor/matt-pocock/skills/engineering/domain-modeling",
  "effect-ts": "vendor/effect-ts/skills/effect-ts",
  "grill-with-docs": "vendor/matt-pocock/skills/engineering/grill-with-docs",
  grilling: "vendor/matt-pocock/skills/productivity/grilling",
  handoff: "vendor/matt-pocock/skills/productivity/handoff",
  implement: "vendor/matt-pocock/skills/engineering/implement",
  "improve-codebase-architecture": "vendor/matt-pocock/skills/engineering/improve-codebase-architecture",
  prototype: "vendor/matt-pocock/skills/engineering/prototype",
  "resolving-merge-conflicts": "vendor/matt-pocock/skills/engineering/resolving-merge-conflicts",
  tdd: "vendor/matt-pocock/skills/engineering/tdd",
  "to-spec": "vendor/matt-pocock/skills/engineering/to-spec",
  "to-tickets": "vendor/matt-pocock/skills/engineering/to-tickets",
  unslop: "vendor/pstack/skills/unslop",
  wizard: "vendor/matt-pocock/skills/engineering/wizard",
} as const;

const OWNED_SKILLS = ["confect", "convex"] as const;

export function syncGuidance(tree: Tree) {
  deleteGeneratedTree(tree, ".keenko");
  copyDirectory(tree, "docs/core", ".keenko/docs/core");
  copyDirectory(tree, "docs/conventions", ".keenko/docs/conventions");
  copyDirectory(tree, "docs/stacks", ".keenko/docs/stacks");

  for (const name of OWNED_SKILLS) {
    copyDirectory(tree, `skills/${name}`, `.keenko/skills/${name}`);
  }
  for (const [name, source] of Object.entries(VENDORED_SKILLS)) {
    writeVendoredAdapter(tree, name, source);
  }

  const skillNames = [...OWNED_SKILLS, ...Object.keys(VENDORED_SKILLS)].toSorted();
  for (const harness of [".agents", ".claude"]) {
    deleteGeneratedSkills(tree, `${harness}/skills`);
    for (const name of skillNames) {
      copyTreeDirectory(tree, `.keenko/skills/${name}`, `${harness}/skills/${name}`);
      tree.write(`${harness}/skills/${name}/.keenko-generated`, "generated by keenko\n");
    }
  }

  for (const [file, template] of [
    ["AGENTS.md", "templates/AGENTS.managed.md"],
    ["CLAUDE.md", "templates/CLAUDE.managed.md"],
  ] as const) {
    const current = tree.read(file, "utf-8") ?? "";
    tree.write(file, renderManagedBlock(current, readSource(template), file));
  }

  for (const [file, template] of [
    ["CONTEXT.md", "templates/project-context.md"],
    ["docs/project/architecture.md", "templates/project-architecture.md"],
    ["docs/project/overrides.md", "templates/project-overrides.md"],
    ["docs/project/ui.md", "templates/project-ui.md"],
  ] as const) {
    if (!tree.exists(file)) {
      tree.write(file, readSource(template));
    }
  }

  const hashes = hashTreeFiles(tree, [".keenko/docs/", ".keenko/skills/"]);
  tree.write(".keenko/manifest.json", `${JSON.stringify({ files: hashes, generatedBy: "keenko", schemaVersion: 1 }, null, 2)}\n`);
}

export function verifyGuidance(tree: Tree) {
  const text = tree.read(".keenko/manifest.json", "utf-8");
  if (text === null) {
    throw new Error("Missing generated Keenko guidance. Run 'bunx nx g keenko:sync'.");
  }
  const parsed: unknown = JSON.parse(text);
  if (parsed === null || typeof parsed !== "object" || Array.isArray(parsed) || !("files" in parsed)) {
    throw new Error("Invalid .keenko/manifest.json");
  }
  const { files } = parsed;
  if (files === null || typeof files !== "object" || Array.isArray(files)) {
    throw new Error("Invalid files in .keenko/manifest.json");
  }
  const actual = hashTreeFiles(tree, [".keenko/docs/", ".keenko/skills/"]);
  if (JSON.stringify(actual) !== JSON.stringify(files)) {
    throw new Error("Generated Keenko guidance has drifted. Run 'bunx nx g keenko:sync'.");
  }
  for (const harness of [".agents", ".claude"]) {
    for (const [file, hash] of Object.entries(actual)) {
      if (!file.startsWith(".keenko/skills/")) {
        continue;
      }
      const native = file.replace(".keenko/skills/", `${harness}/skills/`);
      if (hashContent(tree.read(native) ?? Buffer.from("")) !== hash) {
        throw new Error(`Generated native skill differs from the canonical snapshot: ${native}`);
      }
    }
  }
}

function writeVendoredAdapter(tree: Tree, name: string, source: string) {
  const target = `.keenko/skills/${name}`;
  const upstream = readSource(`${source}/SKILL.md`);
  const frontmatter =
    /^---\n[\s\S]*?\n---\n/u.exec(upstream)?.[0] ?? `---\nname: ${name}\ndescription: Keenko-adapted upstream workflow.\n---\n`;
  tree.write(
    `${target}/SKILL.md`,
    `${frontmatter}\n# Keenko adapter\n\nRead \`references/upstream/SKILL.md\` and apply it below project and Keenko authority. Do not infer permission to commit, push, merge, deploy, publish, install dependencies, or perform destructive actions. Only invoke skills installed in this snapshot.\n`
  );
  copyDirectory(tree, source, `${target}/references/upstream`);
  const vendor = source.split("/").slice(0, 2).join("/");
  tree.write(`${target}/UPSTREAM_LICENSE`, readSource(`${vendor}/LICENSE`));
  tree.write(`${target}/UPSTREAM_PROVENANCE.json`, readSource(`${vendor}/VENDORED.json`));
}

function copyDirectory(tree: Tree, source: string, target: string, include: (file: string) => boolean = () => true) {
  const root = sourcePath(source);
  for (const file of walk(root)) {
    const relative = path.relative(root, file).replaceAll("\\", "/");
    if (include(relative)) {
      tree.write(`${target}/${relative}`, readFileSync(file));
    }
  }
}

function copyTreeDirectory(tree: Tree, source: string, target: string) {
  for (const change of tree.listChanges()) {
    if (change.path.startsWith(`${source}/`) && change.content !== null) {
      tree.write(change.path.replace(source, target), change.content);
    }
  }
}

function deleteGeneratedTree(tree: Tree, root: string) {
  for (const file of listTreeFiles(tree, root)) {
    tree.delete(file);
  }
}

function deleteGeneratedSkills(tree: Tree, root: string) {
  for (const directory of tree.children(root)) {
    if (tree.exists(`${root}/${directory}/.keenko-generated`)) {
      for (const file of listTreeFiles(tree, `${root}/${directory}`)) {
        tree.delete(file);
      }
    }
  }
}

function listTreeFiles(tree: Tree, root: string): string[] {
  if (tree.isFile(root)) {
    return [root];
  }
  return tree.children(root).flatMap((child) => listTreeFiles(tree, `${root}/${child}`));
}

function renderManagedBlock(current: string, template: string, file: string) {
  const block = `${START}\n\n${template.trim()}\n${END}`;
  const start = current.indexOf(START);
  const end = current.indexOf(END);
  if ((start === -1) !== (end === -1) || (start !== -1 && end < start)) {
    throw new Error(`Malformed Keenko managed block in ${file}`);
  }
  if (start === -1) {
    return current.trim().length === 0 ? `${block}\n` : `${current.trimEnd()}\n\n${block}\n`;
  }
  return `${current.slice(0, start)}${block}${current.slice(end + END.length)}`;
}

function hashTreeFiles(tree: Tree, roots: string[]) {
  const files = roots.flatMap((root) => listTreeFiles(tree, root)).toSorted();
  return Object.fromEntries(files.map((file) => [file, hashContent(tree.read(file) ?? Buffer.from(""))]));
}

function hashContent(content: Buffer | string) {
  return createHash("sha256").update(content).digest("hex");
}

function sourcePath(relative: string) {
  const result = path.join(PACKAGE_ROOT, relative);
  if (!existsSync(result)) {
    throw new Error(`Missing packaged Keenko asset: ${relative}`);
  }
  return result;
}

function packageRoot() {
  const source = path.resolve(import.meta.dirname, "..");
  return existsSync(path.join(source, "package.json")) ? source : path.resolve(source, "..");
}

function readSource(relative: string) {
  return readFileSync(sourcePath(relative), "utf-8");
}

function walk(root: string): string[] {
  return readdirSync(root).flatMap((name) => {
    const entry = path.join(root, name);
    return statSync(entry).isDirectory() ? walk(entry) : [entry];
  });
}
