import type { Tree } from "@nx/devkit";
import { createHash } from "node:crypto";
import { existsSync, readFileSync, readdirSync, statSync } from "node:fs";
import path from "node:path";

const PACKAGE_ROOT = packageRoot();
const START = "<!-- keenko:start -->";
const END = "<!-- keenko:end -->";
const PROJECT_SCAFFOLD = ["CONTEXT.md", "docs/project/architecture.md", "docs/project/overrides.md", "docs/project/ui.md"] as const;

const VENDORED_SKILLS = {
  "ask-matt": "vendor/matt-pocock/skills/engineering/ask-matt",
  "code-review": "vendor/matt-pocock/skills/engineering/code-review",
  "codebase-design": "vendor/matt-pocock/skills/engineering/codebase-design",
  "diagnosing-bugs": "vendor/matt-pocock/skills/engineering/diagnosing-bugs",
  "domain-modeling": "vendor/matt-pocock/skills/engineering/domain-modeling",
  "effect-ts": "vendor/effect-ts/skills/effect-ts",
  "grill-with-docs": "vendor/matt-pocock/skills/engineering/grill-with-docs",
  grilling: "vendor/matt-pocock/skills/productivity/grilling",
  handoff: "vendor/matt-pocock/skills/productivity/handoff",
  implement: "vendor/matt-pocock/skills/engineering/implement",
  "improve-codebase-architecture": "vendor/matt-pocock/skills/engineering/improve-codebase-architecture",
  prototype: "vendor/matt-pocock/skills/engineering/prototype",
  "resolving-merge-conflicts": "vendor/matt-pocock/skills/engineering/resolving-merge-conflicts",
  tdd: "vendor/matt-pocock/skills/engineering/tdd",
  "to-spec": "vendor/matt-pocock/skills/engineering/to-spec",
  "to-tickets": "vendor/matt-pocock/skills/engineering/to-tickets",
  unslop: "vendor/pstack/skills/unslop",
  wizard: "vendor/matt-pocock/skills/engineering/wizard",
} as const;

const OWNED_SKILLS = ["confect", "convex"] as const;

export function syncGuidance(tree: Tree) {
  deleteGeneratedTree(tree, ".keenko");
  copyDirectory(tree, "docs/core", ".keenko/docs/core");
  copyDirectory(tree, "docs/conventions", ".keenko/docs/conventions");
  copyDirectory(tree, "docs/stacks", ".keenko/docs/stacks");

  for (const name of OWNED_SKILLS) {
    copyDirectory(tree, `skills/${name}`, `.keenko/skills/${name}`);
  }
  for (const [name, source] of Object.entries(VENDORED_SKILLS)) {
    writeVendoredAdapter(tree, name, source);
  }

  const skillNames = [...OWNED_SKILLS, ...Object.keys(VENDORED_SKILLS)].toSorted();
  for (const harness of [".agents", ".claude"]) {
    deleteGeneratedSkills(tree, `${harness}/skills`);
    for (const name of skillNames) {
      copyTreeDirectory(tree, `.keenko/skills/${name}`, `${harness}/skills/${name}`);
      tree.write(`${harness}/skills/${name}/.keenko-generated`, "generated by keenko\n");
    }
  }

  for (const [file, template] of [
    ["AGENTS.md", "templates/AGENTS.managed.md"],
    ["CLAUDE.md", "templates/CLAUDE.managed.md"],
  ] as const) {
    const current = tree.read(file, "utf-8") ?? "";
    tree.write(file, renderManagedBlock(current, readSource(template), file));
  }

  for (const [file, template] of [
    ["CONTEXT.md", "templates/project-context.md"],
    ["docs/project/architecture.md", "templates/project-architecture.md"],
    ["docs/project/overrides.md", "templates/project-overrides.md"],
    ["docs/project/ui.md", "templates/project-ui.md"],
  ] as const) {
    if (!tree.exists(file)) {
      tree.write(file, readSource(template));
    }
  }

  const hashes = hashTreeFiles(tree, [".keenko/docs/", ".keenko/skills/"]);
  tree.write(".keenko/manifest.json", `${JSON.stringify({ files: hashes, generatedBy: "keenko", schemaVersion: 1 }, null, 2)}\n`);
}

export function verifyGuidance(tree: Tree) {
  const text = tree.read(".keenko/manifest.json", "utf-8");
  if (text === null) {
    throw new Error("Missing generated Keenko guidance. Run 'bunx nx g keenko:sync'.");
  }
  const parsed = object(JSON.parse(text), ".keenko/manifest.json");
  if (parsed.generatedBy !== "keenko" || parsed.schemaVersion !== 1) {
    throw new Error("Invalid .keenko/manifest.json");
  }
  const files = object(parsed.files, ".keenko/manifest.json.files");
  const actual = hashTreeFiles(tree, [".keenko/docs/", ".keenko/skills/"]);
  if (JSON.stringify(actual) !== JSON.stringify(files)) {
    throw new Error("Generated Keenko guidance has drifted. Run 'bunx nx g keenko:sync'.");
  }

  for (const harness of [".agents", ".claude"]) {
    for (const [file, hash] of Object.entries(actual)) {
      if (!file.startsWith(".keenko/skills/") || typeof hash !== "string") {
        continue;
      }
      const native = file.replace(".keenko/skills/", `${harness}/skills/`);
      if (hashContent(tree.read(native) ?? Buffer.from("")) !== hash) {
        throw new Error(`Generated native skill differs from the canonical snapshot: ${native}`);
      }
    }
    for (const skill of [...OWNED_SKILLS, ...Object.keys(VENDORED_SKILLS)]) {
      if (tree.read(`${harness}/skills/${skill}/.keenko-generated`, "utf-8") !== "generated by keenko\n") {
        throw new Error(`Missing Keenko generated marker for ${harness}/skills/${skill}`);
      }
    }
  }

  for (const [file, template] of [
    ["AGENTS.md", "templates/AGENTS.managed.md"],
    ["CLAUDE.md", "templates/CLAUDE.managed.md"],
  ] as const) {
    verifyManagedBlock(tree.read(file, "utf-8"), readSource(template), file);
  }
  for (const file of PROJECT_SCAFFOLD) {
    if (!tree.exists(file)) {
      throw new Error(`Missing project-owned Keenko scaffold: ${file}`);
    }
  }
}

function writeVendoredAdapter(tree: Tree, name: string, source: string) {
  const target = `.keenko/skills/${name}`;
  const upstream = readSource(`${source}/SKILL.md`);
  const frontmatter =
    /^---\n[\s\S]*?\n---\n/u.exec(upstream)?.[0] ?? `---\nname: ${name}\ndescription: Keenko-adapted upstream workflow.\n---\n`;
  tree.write(
    `${target}/SKILL.md`,
    `${frontmatter}\n# Keenko adapter\n\nRead references/upstream/SKILL.md and apply it below project and Keenko authority. Do not infer permission to commit, push, merge, deploy, publish, install dependencies, or perform destructive actions. Only invoke skills installed in this snapshot.\n`
  );
  copyDirectory(tree, source, `${target}/references/upstream`);
  const vendor = source.split("/").slice(0, 2).join("/");
  tree.write(`${target}/UPSTREAM_LICENSE`, readSource(`${vendor}/LICENSE`));
  tree.write(`${target}/UPSTREAM_PROVENANCE.json`, readSource(`${vendor}/VENDORED.json`));
}

function copyDirectory(tree: Tree, source: string, target: string, include: (file: string) => boolean = () => true) {
  const root = sourcePath(source);
  for (const file of walk(root)) {
    const relative = path.relative(root, file).replaceAll("\\", "/");
    if (include(relative)) {
      tree.write(`${target}/${relative}`, readFileSync(file));
    }
  }
}

function copyTreeDirectory(tree: Tree, source: string, target: string) {
  for (const file of listTreeFiles(tree, source)) {
    const content = tree.read(file);
    if (content !== null) {
      tree.write(file.replace(source, target), content);
    }
  }
}

function deleteGeneratedTree(tree: Tree, root: string) {
  for (const file of listTreeFiles(tree, root)) {
    tree.delete(file);
  }
}

function deleteGeneratedSkills(tree: Tree, root: string) {
  for (const directory of tree.children(root)) {
    if (tree.exists(`${root}/${directory}/.keenko-generated`)) {
      for (const file of listTreeFiles(tree, `${root}/${directory}`)) {
        tree.delete(file);
      }
    }
  }
}

function listTreeFiles(tree: Tree, root: string): string[] {
  if (tree.isFile(root)) {
    return [root];
  }
  return tree.children(root).flatMap((child) => listTreeFiles(tree, `${root}/${child}`));
}

function renderManagedBlock(current: string, template: string, file: string) {
  const block = managedBlock(template);
  const range = managedRange(current, file);
  if (range === null) {
    if (current.length === 0) {
      return `${block}\n`;
    }
    const separator = current.endsWith("\n\n") ? "" : current.endsWith("\n") ? "\n" : "\n\n";
    return `${current}${separator}${block}\n`;
  }
  return `${current.slice(0, range.start)}${block}${current.slice(range.end)}`;
}

function verifyManagedBlock(current: string | null, template: string, file: string) {
  if (current === null) {
    throw new Error(`Missing ${file}`);
  }
  const range = managedRange(current, file);
  if (range === null) {
    throw new Error(`Missing Keenko managed block in ${file}. Run 'bunx nx g keenko:sync'.`);
  }
  const actual = current.slice(range.start, range.end);
  if (actual !== managedBlock(template)) {
    throw new Error(`Keenko managed block has drifted in ${file}. Run 'bunx nx g keenko:sync'.`);
  }
}

function managedRange(current: string, file: string): { end: number; start: number } | null {
  const starts = markerPositions(current, START);
  const ends = markerPositions(current, END);
  if (starts.length === 0 && ends.length === 0) {
    return null;
  }
  const [start] = starts;
  const [end] = ends;
  if (starts.length !== 1 || ends.length !== 1 || start === undefined || end === undefined || end < start) {
    throw new Error(
      `Invalid Keenko managed block in ${file}: expected exactly one ${START} followed by exactly one ${END}. Remove duplicate or stray markers, then run 'bunx nx g keenko:sync'.`
    );
  }
  return { end: end + END.length, start };
}

function markerPositions(current: string, marker: string) {
  const positions: number[] = [];
  let offset = 0;
  while (offset <= current.length) {
    const index = current.indexOf(marker, offset);
    if (index === -1) {
      break;
    }
    positions.push(index);
    offset = index + marker.length;
  }
  return positions;
}

function managedBlock(template: string) {
  return `${START}\n\n${template.trim()}\n${END}`;
}

function hashTreeFiles(tree: Tree, roots: string[]) {
  const files = roots.flatMap((root) => listTreeFiles(tree, root.replace(/\/+$/u, ""))).toSorted();
  return Object.fromEntries(files.map((file) => [file, hashContent(tree.read(file) ?? Buffer.from(""))]));
}

function hashContent(content: Buffer | string) {
  return createHash("sha256").update(content).digest("hex");
}

function object(value: unknown, label: string): Record<string, unknown> {
  if (value === null || typeof value !== "object" || Array.isArray(value)) {
    throw new TypeError(`${label} must be an object`);
  }
  return Object.fromEntries(Object.entries(value));
}

function sourcePath(relative: string) {
  const result = path.join(PACKAGE_ROOT, relative);
  if (!existsSync(result)) {
    throw new Error(`Missing packaged Keenko asset: ${relative}`);
  }
  return result;
}

function packageRoot() {
  const source = path.resolve(import.meta.dirname, "..");
  return existsSync(path.join(source, "package.json")) ? source : path.resolve(source, "..");
}

function readSource(relative: string) {
  return readFileSync(sourcePath(relative), "utf-8");
}

function walk(root: string): string[] {
  return readdirSync(root).flatMap((name) => {
    const entry = path.join(root, name);
    return statSync(entry).isDirectory() ? walk(entry) : [entry];
  });
}
